// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRQ3tUus75KTXj5fVU4Jim1Z6giS1Luto',
    appId: '1:115394871602:web:311ce363742cfb0b49172b',
    messagingSenderId: '115394871602',
    projectId: 'ebbin-e0e1e',
    authDomain: 'ebbin-e0e1e.firebaseapp.com',
    storageBucket: 'ebbin-e0e1e.appspot.com',
    measurementId: 'G-M3BQDCKZY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw6wsi2yPacpuJfiwlq4ohrUgrJjJ4z_0',
    appId: '1:115394871602:android:9575786b0426197d49172b',
    messagingSenderId: '115394871602',
    projectId: 'ebbin-e0e1e',
    storageBucket: 'ebbin-e0e1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk2fOzhu5_7rixteYOcUYD90Nyzzhg8GA',
    appId: '1:115394871602:ios:b8240056e1eb922449172b',
    messagingSenderId: '115394871602',
    projectId: 'ebbin-e0e1e',
    storageBucket: 'ebbin-e0e1e.appspot.com',
    iosClientId: '115394871602-behvnnedu355rfqgs3g0dgokns9nu01s.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebbin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk2fOzhu5_7rixteYOcUYD90Nyzzhg8GA',
    appId: '1:115394871602:ios:f0f1a0b1f09f25fc49172b',
    messagingSenderId: '115394871602',
    projectId: 'ebbin-e0e1e',
    storageBucket: 'ebbin-e0e1e.appspot.com',
    iosClientId: '115394871602-8ua1n0h1e5mnn286vk0l91h5ejumeqe9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebbin.RunnerTests',
  );
}
